# Generated by Django 4.2 on 2023-04-30 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='kg_or_ltr',
            field=models.CharField(choices=[('Kg', 'Kg'), ('Liter', 'Liter')], default='Kg', max_length=5),
        ),
    ]
