# Generated by Django 4.2 on 2023-04-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_quentity',
            field=models.IntegerField(default=1),
        ),
    ]
